linters-settings:
  govet:
    shadow: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/shosato0306

linters:
  enable:
    - govet
    - gosimple
    - gofmt
    - goimports
    - errcheck
    - staticcheck
    - unused
    - gocritic
    - gocyclo
    - ineffassign
    - typecheck
    - gosec
  disable:
    - gochecknoinits

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - third_party

run:
  deadline: 5m
  tests: true
