version: '3.1'

services:
  db:
    image: mysql:8.4
    container_name: mydb
    environment:
      MYSQL_DATABASE: 'myapp'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb:
