name: golangci-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.57
          args: ./...
